(define (proc n)
  (flatmap (lambda (i)
         (flatmap (lambda (j)
                (map (lambda (k) (list i j k))
                     (enumerate-interval 1 n)))
              (enumerate-interval 1 (- j 1))))
       (enumerate-interval 1 n)))

(define (solution n s)
  (filter (lambda (x)
            (= s (+ (car x) (cadr x) (caddr x))))
          (proc n)))
