(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
    (if (eq? p password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              ((eq? m 'check-pass) #t)
              (else (error "Unknown request: MAKE-ACCOUNT"
                           m)))
        (begin (display "Incorrect password")
               #f)))
  dispatch)

(define (make-joint account password new-password)
  (if (account password 'check-pass)
      (lambda (p m) (if (eq? p new-password)
                        (account password m)
                        (display "Incorrect password")))
      (display "Incorrect password")))
